"""Tests for ``LLMUsage`` model — immutable, append-only, computed total_tokens."""
from __future__ import annotations

import uuid

import pytest

from models.llm_usage import LLMUsage


class TestLLMUsageModel:
    """Cover LLMUsage fields — model, task_type, tokens, cost, duration."""

    @pytest.mark.unit
    def test_required_fields(self) -> None:
        """Minimal required fields produce a valid instance."""
        usage = LLMUsage(
            organization_id=uuid.uuid4(),
            model="gpt-4o",
            task_type="chat.completion",
        )
        assert usage.organization_id is not None
        assert usage.model == "gpt-4o"
        assert usage.task_type == "chat.completion"

    @pytest.mark.unit
    def test_defaults_configured(self) -> None:
        """Token/cost/duration columns have server_defaults."""
        for col_name in [
            "prompt_tokens",
            "completion_tokens",
            "cache_read_input_tokens",
            "cache_creation_input_tokens",
            "cost_estimate",
            "duration_ms",
        ]:
            col = LLMUsage.__table__.columns[col_name]
            assert col.server_default is not None, f"{col_name} missing server_default"

    @pytest.mark.unit
    def test_total_tokens_column(self) -> None:
        """total_tokens is a Computed column (generated by DB)."""
        usage = LLMUsage(
            organization_id=uuid.uuid4(),
            model="gpt-4o",
            task_type="chat.completion",
            prompt_tokens=10,
            completion_tokens=5,
        )
        # total_tokens is server-computed, so Python-level value follows the
        # mapped_column default (also 0 in Python, but DB will compute).
        col = LLMUsage.__table__.columns["total_tokens"]
        assert col is not None
        assert col.computed is not None

    @pytest.mark.unit
    def test_table_name(self) -> None:
        """Table name is llm_usage."""
        assert LLMUsage.__tablename__ == "llm_usage"

    @pytest.mark.unit
    def test_uses_created_at_mixin(self) -> None:
        """LLMUsage has created_at but NOT updated_at."""
        usage = LLMUsage(
            organization_id=uuid.uuid4(),
            model="gpt-4o",
            task_type="chat.completion",
        )
        assert hasattr(usage, "created_at")
        assert not hasattr(usage, "updated_at")

    @pytest.mark.unit
    def test_repr(self) -> None:
        """repr includes model and total_tokens."""
        usage = LLMUsage(
            organization_id=uuid.uuid4(),
            model="gpt-4o",
            task_type="chat.completion",
        )
        assert "LLMUsage" in repr(usage)
        assert "gpt-4o" in repr(usage)
