apiVersion: v1
kind: Service
metadata:
  name: {{ include "openzep.fullname" . }}-api
  labels:
    {{- include "openzep.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: {{ .Values.api.containerPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "openzep.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
