apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openzync.fullname" . }}-worker
  labels:
    {{- include "openzync.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      {{- include "openzync.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        {{- include "openzync.labels" . | nindent 8 }}
        app.kubernetes.io/component: worker
    spec:
      containers:
        - name: worker
          image: "{{ .Values.global.imageRegistry }}/{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}"
          imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "openzync.fullname" . }}-config
            - secretRef:
                name: {{ include "openzync.fullname" . }}-secrets
                optional: true
          livenessProbe:
            exec:
              command:
                - python
                - "-c"
                - "import redis; r=redis.from_url('$REDIS_URL'); r.ping()"
            initialDelaySeconds: {{ .Values.worker.health.initialDelaySeconds }}
            periodSeconds: {{ .Values.worker.health.periodSeconds }}
            timeoutSeconds: {{ .Values.worker.health.timeoutSeconds }}
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
