{{- if .Values.api.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "openzync.fullname" . }}-api
  labels:
    {{- include "openzync.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.api.ingress.tls.enabled }}
    cert-manager.io/cluster-issuer: letsencrypt-prod
    {{- end }}
spec:
  {{- if .Values.api.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.api.ingress.host | quote }}
      secretName: {{ .Values.api.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.api.ingress.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "openzync.fullname" . }}-api
                port:
                  number: 80
{{- end }}
