"""Unit tests for email configuration and message building."""

from __future__ import annotations

import pytest


@pytest.mark.unit
class TestEmailConfig:
    """EmailConfig construction and from_settings."""

    def test_constructs_with_all_fields(self) -> None:
        """EmailConfig stores all SMTP fields."""
        from core.email import EmailConfig

        config = EmailConfig(
            host="smtp.example.com",
            port=587,
            username="user",
            password="pass",
            from_addr="noreply@example.com",
            use_tls=False,
            start_tls=True,
        )
        assert config.HOST == "smtp.example.com"
        assert config.PORT == 587
        assert config.USERNAME == "user"
        assert config.PASSWORD == "pass"
        assert config.FROM_ADDR == "noreply@example.com"
        assert config.USE_TLS is False
        assert config.START_TLS is True

    def test_from_settings_populates_from_settings(self) -> None:
        """from_settings creates config from the global Settings singleton."""
        from core.config import get_settings
        from core.email import EmailConfig

        config = EmailConfig.from_settings(get_settings())

        # Settings defaults from conftest + model defaults
        assert config.HOST == "localhost"
        assert config.PORT == 587
        assert config.USERNAME == ""
        assert config.PASSWORD == ""
        assert config.FROM_ADDR == "noreply@openzync.tech"
        assert config.USE_TLS is False
        assert config.START_TLS is True

    def test_slots_prevent_dynamic_attrs(self) -> None:
        """__slots__ prevents setting undeclared attributes."""
        from core.email import EmailConfig

        config = EmailConfig(
            host="localhost",
            port=587,
            username="",
            password="",
            from_addr="a@b.com",
            use_tls=False,
            start_tls=True,
        )
        with pytest.raises(AttributeError):
            config.unknown_attr = "value"  # type: ignore[attr-defined]


@pytest.mark.unit
class TestBuildEmailMessage:
    """build_email_message constructs proper EmailMessage objects."""

    def test_basic_email_message(self) -> None:
        """Email has correct From, To, Subject headers."""
        from core.email import build_email_message

        msg = build_email_message(
            to="user@example.com",
            subject="Test Subject",
            html_body="<p>Hello</p>",
            text_body="Hello",
            from_addr="noreply@openzync.tech",
        )
        assert msg["From"] == "noreply@openzync.tech"
        assert msg["To"] == "user@example.com"
        assert msg["Subject"] == "Test Subject"

    def test_default_from_addr(self) -> None:
        """Default from_addr is noreply@openzync.tech."""
        from core.email import build_email_message

        msg = build_email_message(
            to="user@example.com",
            subject="Test",
            html_body="<p>Body</p>",
        )
        assert msg["From"] == "noreply@openzync.tech"

    def test_html_and_plain_text_parts(self) -> None:
        """Message has both HTML and plain text alternatives."""
        from core.email import build_email_message

        msg = build_email_message(
            to="user@example.com",
            subject="Test",
            html_body="<p>Hello <b>World</b></p>",
            text_body="Hello World",
        )
        # EmailMessage stores payload as a multipart
        assert len(msg.get_payload()) == 2
        plain_part, html_part = msg.get_payload()
        assert plain_part.get_content_type() == "text/plain"
        assert html_part.get_content_type() == "text/html"
        assert plain_part.get_payload().rstrip() == "Hello World"
        assert html_part.get_payload().rstrip() == "<p>Hello <b>World</b></p>"

    def test_plain_text_auto_generated_from_html(self) -> None:
        """Plain text is auto-generated by stripping HTML when not provided."""
        from core.email import build_email_message

        msg = build_email_message(
            to="user@example.com",
            subject="Test",
            html_body="<p>Hello <b>World</b></p><p>Line 2</p>",
        )
        plain_part, _html_part = msg.get_payload()
        plain_text = plain_part.get_payload()
        assert "Hello" in plain_text
        assert "World" in plain_text
        assert "Line 2" in plain_text
        assert "<b>" not in plain_text
        assert "<p>" not in plain_text

    def test_plain_text_strips_nested_html(self) -> None:
        """Auto-generated plain text strips all HTML tags."""
        from core.email import build_email_message

        msg = build_email_message(
            to="u@e.com",
            subject="S",
            html_body="<div><h1>Title</h1><p>Body with <a href='x'>link</a></p></div>",
        )
        plain_part, _html_part = msg.get_payload()
        plain_text = plain_part.get_payload()
        assert "Title" in plain_text
        assert "Body with" in plain_text
        assert "link" in plain_text
        assert "<div>" not in plain_text
        assert "</a>" not in plain_text

    def test_content_types_correct(self) -> None:
        """Message has multipart/alternative content type."""
        from core.email import build_email_message

        msg = build_email_message(
            to="u@e.com",
            subject="T",
            html_body="<p>Body</p>",
            text_body="Body",
        )
        assert "multipart/alternative" in msg.get_content_type()
