"""SecurityHeadersMiddleware — sets security-related HTTP response headers.

Implemented as raw ASGI middleware (no BaseHTTPMiddleware overhead) to ensure
headers are applied to EVERY response including 404, 429, and 500 responses
generated by other middleware.

Headers set:
    Content-Security-Policy      — prevents XSS by restricting script sources
    Strict-Transport-Security    — enforces HTTPS (HSTS)
    X-Content-Type-Options       — prevents MIME-type sniffing
    X-Frame-Options              — prevents clickjacking (DENY)
    Referrer-Policy              — controls referrer header leakage
"""

from __future__ import annotations

import logging
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from starlette.types import ASGIApp, Receive, Scope, Send

logger = logging.getLogger(__name__)

# ── Default headers ──────────────────────────────────────────────────────────
# These can be overridden per-environment via constructor arguments or
# environment variables.  The CSP includes 'unsafe-inline' for Swagger UI
# (docs/redoc) — tighten in production when the docs endpoint is disabled.

DEFAULT_SECURITY_HEADERS: dict[str, str] = {
    "Content-Security-Policy": (
        "default-src 'self'; "
        "script-src 'self' 'unsafe-inline'; "
        "style-src 'self' 'unsafe-inline'; "
        "img-src 'self' data:; "
        "connect-src 'self'"
    ),
    "Strict-Transport-Security": "max-age=31536000; includeSubDomains",
    "X-Content-Type-Options": "nosniff",
    "X-Frame-Options": "DENY",
    "Referrer-Policy": "strict-origin-when-cross-origin",
}


class SecurityHeadersMiddleware:
    """ASGI middleware that sets security response headers on every response.

    Headers are injected into the ``http.response.start`` message so they
    apply to ALL responses, including those generated by upstream middleware
    (429 from RateLimitMiddleware, 401 from AuthMiddleware, 500 from
    exception handlers, etc.).

    Args:
        app: The inner ASGI application.
        headers: Optional dict of header overrides merged over defaults.
    """

    def __init__(
        self,
        app: ASGIApp,
        headers: dict[str, str] | None = None,
    ) -> None:
        self.app = app
        self._headers: dict[str, str] = {**DEFAULT_SECURITY_HEADERS}
        if headers:
            self._headers.update(headers)

    async def __call__(
        self, scope: Scope, receive: Receive, send: Send
    ) -> None:
        """Apply security headers to every HTTP response.

        Args:
            scope: The ASGI connection scope.
            receive: The ASGI receive callable.
            send: The ASGI send callable.
        """
        if scope["type"] != "http":
            await self.app(scope, receive, send)
            return

        async def send_wrapper(message: dict[str, Any]) -> None:
            if message["type"] == "http.response.start":
                raw_headers: list[tuple[bytes, bytes]] = list(
                    message.get("headers", [])
                )
                for name, value in self._headers.items():
                    raw_headers.append(
                        (name.lower().encode("ascii"), value.encode("ascii"))
                    )
                message["headers"] = raw_headers
            await send(message)

        await self.app(scope, receive, send_wrapper)
