#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────────────────────────
# OpenZync — Development environment quick-start
# ──────────────────────────────────────────────────────────────────────────────
# Idempotent: safe to run multiple times.
# Dependencies: Docker, Python 3.11+, docker-compose-plugin.
#
# Credentials: read from environment variables with no hardcoded defaults.
#   $POSTGRES_USER      (default: openzync)
#   $POSTGRES_PASSWORD  (default: openzync — only for local Docker containers)
#   $POSTGRES_DB        (default: openzync)
# ──────────────────────────────────────────────────────────────────────────────
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# ── Configurable defaults (override via env) ──────────────────────────────────
POSTGRES_USER="${POSTGRES_USER:-openzync}"
POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-}"
POSTGRES_DB="${POSTGRES_DB:-openzync}"
OZ_SECRET_KEY="${OZ_SECRET_KEY:-}"

# ── Colour helpers ────────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

info()  { echo -e "${CYAN}[INFO]${NC}  $*"; }
ok()    { echo -e "${GREEN}[OK]${NC}    $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
err()   { echo -e "${RED}[ERROR]${NC} $*"; }

# ── Prerequisites ─────────────────────────────────────────────────────────────
info "Checking prerequisites..."

command -v docker >/dev/null 2>&1 || { err "Docker is required but not installed."; exit 1; }
command -v python3 >/dev/null 2>&1 || { err "Python 3 is required but not installed."; exit 1; }

docker compose version >/dev/null 2>&1 || {
    err "Docker Compose (v2) plugin not found."
    err "Install: https://docs.docker.com/compose/install/"
    exit 1
}

ok "All prerequisites found."

# ── Warn about default credentials ────────────────────────────────────────────
if [ -z "$POSTGRES_PASSWORD" ]; then
    warn "POSTGRES_PASSWORD not set. Using 'openzync' for local Docker container only."
    warn "  export POSTGRES_PASSWORD=<your-password>"
    POSTGRES_PASSWORD="openzync"
fi

if [ -z "$OZ_SECRET_KEY" ]; then
    warn "OZ_SECRET_KEY not set. Generating a temporary dev key."
    warn "  Set it: export OZ_SECRET_KEY=\$(python3 -c \"import secrets; print(secrets.token_urlsafe(48))\")"
    OZ_SECRET_KEY="dev-secret-key-that-is-at-least-32-characters-long"
fi

# ── Environment file ──────────────────────────────────────────────────────────
ENV_FILE="$PROJECT_ROOT/.env"

if [ ! -f "$ENV_FILE" ]; then
    info "Creating $ENV_FILE with development defaults..."
    cat > "$ENV_FILE" <<- EOF
# ── OpenZync Development Configuration ────────────────────────────────
# Generated by scripts/run_dev.sh — override values as needed.
# NEVER commit this file to version control.

# Database (credentials from env or script defaults)
OZ_DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@localhost:5432/${POSTGRES_DB}
OZ_REDIS_URL=redis://localhost:6379/0
OZ_FALKORDB_URL=redis://localhost:6380

# Secrets (change in production!)
OZ_SECRET_KEY=${OZ_SECRET_KEY}

# Environment
OZ_ENVIRONMENT=development
OZ_LOG_LEVEL=DEBUG

# LLM
OZ_LLM_BACKEND=ollama
OLLAMA_BASE_URL=http://host.docker.internal:11434

# CORS
OZ_CORS_ORIGINS=http://localhost:3000,http://localhost:5173

# Rate limiting (generous in dev)
OZ_RATE_LIMIT_IP_MAX=100
EOF
    ok ".env file created."
else
    warn "$ENV_FILE already exists — skipping."
fi

# ── Start infrastructure ──────────────────────────────────────────────────────
COMPOSE_FILE="$PROJECT_ROOT/infra/docker-compose.yml"
SERVICES="postgres redis falkordb"

if [ -f "$COMPOSE_FILE" ]; then
    info "Starting Docker Compose services: $SERVICES ..."
    docker compose -f "$COMPOSE_FILE" up -d $SERVICES 2>/dev/null || {
        warn "Docker Compose failed — starting containers individually as fallback."

        docker run -d --name openzync-postgres \
            -e POSTGRES_USER="$POSTGRES_USER" \
            -e POSTGRES_PASSWORD="$POSTGRES_PASSWORD" \
            -e POSTGRES_DB="$POSTGRES_DB" \
            -p 5432:5432 \
            postgres:15 2>/dev/null || true

        docker run -d --name openzync-redis \
            -p 6379:6379 \
            redis:7-alpine 2>/dev/null || true

        docker run -d --name openzync-falkordb \
            -p 6380:6379 \
            falkordb/falkordb:latest 2>/dev/null || true
    }
else
    warn "No Docker Compose file found at $COMPOSE_FILE — assuming services are running externally."
fi

# ── Wait for PostgreSQL ───────────────────────────────────────────────────────
info "Waiting for PostgreSQL to become available..."
for i in $(seq 1 30); do
    if docker exec openzync-postgres pg_isready -U "$POSTGRES_USER" >/dev/null 2>&1; then
        ok "PostgreSQL is ready."
        break
    fi
    if [ "$i" -eq 30 ]; then
        warn "PostgreSQL did not become ready in time — continuing anyway."
    fi
    sleep 2
done

# ── Install dependencies ──────────────────────────────────────────────────────
info "Installing Python dependencies..."
cd "$PROJECT_ROOT"
pip install -e ".[dev]" -q 2>&1 | tail -1
ok "Dependencies installed."

# ── Run migrations ────────────────────────────────────────────────────────────
info "Running database migrations..."
cd "$PROJECT_ROOT"
alembic upgrade head 2>&1 || {
    warn "Alembic migration failed — you may need to create the database first:"
    warn "  docker exec -it openzync-postgres createdb -U $POSTGRES_USER $POSTGRES_DB"
}
ok "Migrations applied."

# ── Generate dev API key ──────────────────────────────────────────────────────
info "Generating development API key..."
cd "$PROJECT_ROOT"
python scripts/create_dev_key.py

# ── Summary ───────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}══════════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}  OpenZync development environment is ready!${NC}"
echo -e "${GREEN}══════════════════════════════════════════════════════════════${NC}"
echo ""
echo -e "  Start the API server:"
echo -e "    ${CYAN}uvicorn services.api.asgi:app --reload --port 8000${NC}"
echo ""
echo -e "  Run tests:"
echo -e "    ${CYAN}make test${NC}        (unit tests)"
echo -e "    ${CYAN}make test-all${NC}    (all tests)"
echo ""
echo -e "  Environment:"
echo -e "    ${CYAN}source .env${NC}      (load env vars into shell)"
echo ""
