"""GraphObservation model — observation records surfaced from graph-topology analysis.

Observations represent patterns in the graph that can't be extracted from a
single message or triple — things like "Jane upgrades within 2 weeks of every
product launch" or "Entity X and Entity Y always appear together in support
tickets."

This is a **second inference pass** over graph topology (not over raw text),
running after entity extraction (bit 0) and fact extraction (bit 2) have
already populated the graph.  The worker that creates these records is
``compute_observations`` (bit 6).

Table ``graph_observations`` is created via migration 0025.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from enum import StrEnum

from sqlalchemy import ARRAY, Float, ForeignKey, Text, TIMESTAMP, func
from sqlalchemy.dialects.postgresql import JSONB, UUID as SA_UUID
from sqlalchemy.orm import Mapped, mapped_column

from models.base import Base, TimestampMixin


class GraphObservation(TimestampMixin, Base):
    """A single observation about an entity, surfaced from graph-topology analysis.

    Attributes:
        id: UUID primary key.
        organization_id: Owning organization (RLS enforcement).
        project_id: Owning project (project-scoped isolation).
        subject_entity_id: The entity this observation is about.
        related_entity_id: For pair-level observations (e.g., co-occurrence),
            the other entity in the pair.  NULL for entity-level observations
            (e.g., temporal patterns, behavioral patterns).
        observation_type: Type of observation — one of ``ObservationType``
            enum values (e.g. ``co_occurrence``, ``temporal_pattern``).
        content: Natural-language description of the observation.
            Generated by LLM with template-based fallback.
        supporting_fact_ids: UUIDs of ``facts`` rows that support this
            observation.
        supporting_relationship_ids: UUIDs of ``graph_relationships`` rows
            that support this observation.
        confidence: How confident the system is in this observation (0.0–1.0).
        valid_from: Start of this observation's temporal validity.
        valid_to: End of this observation's temporal validity (NULL = open).
        metadata: Arbitrary JSONB metadata for extensibility.
        created_at: Row creation timestamp.
        updated_at: Row last-update timestamp.
    """

    __tablename__ = "graph_observations"

    id: Mapped[uuid.UUID] = mapped_column(
        primary_key=True,
        server_default=func.gen_random_uuid(),
    )
    organization_id: Mapped[uuid.UUID] = mapped_column(nullable=False)
    project_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("projects.id", ondelete="CASCADE"),
        nullable=False,
    )
    subject_entity_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("graph_entities.id", ondelete="CASCADE"),
        nullable=False,
    )
    related_entity_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("graph_entities.id", ondelete="SET NULL"),
        nullable=True,
        comment=(
            "For pair-level observations (e.g. co-occurrence): "
            "the other entity in the pair. NULL for entity-level "
            "observations (temporal patterns, behavioral patterns)."
        ),
    )
    observation_type: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        comment="One of ObservationType enum values.",
    )
    content: Mapped[str] = mapped_column(Text, nullable=False)
    supporting_fact_ids: Mapped[list[uuid.UUID] | None] = mapped_column(
        ARRAY(SA_UUID), nullable=True,
    )
    supporting_relationship_ids: Mapped[list[uuid.UUID] | None] = mapped_column(
        ARRAY(SA_UUID), nullable=True,
    )
    confidence: Mapped[float] = mapped_column(
        Float,
        nullable=False,
        server_default="0.0",
    )
    valid_from: Mapped[datetime | None] = mapped_column(
        TIMESTAMP(timezone=True), nullable=True,
    )
    valid_to: Mapped[datetime | None] = mapped_column(
        TIMESTAMP(timezone=True), nullable=True,
    )
    observation_metadata: Mapped[dict | None] = mapped_column(
        JSONB,
        nullable=True,
        comment="Arbitrary metadata for future extensibility.",
    )

    def __repr__(self) -> str:
        return (
            f"<GraphObservation id={self.id} "
            f"subject={self.subject_entity_id} "
            f"type={self.observation_type!r}>"
        )


class ObservationType(StrEnum):
    """Canonical observation types for graph-topology analysis.

    Adding a new type:
        1. Add a new member here.
        2. Add a detection method in ``ObservationService``.
        3. Add a branch in ``_build_template_description()``.
    """

    CO_OCCURRENCE = "co_occurrence"
    """Two entities co-appear in episodes above a frequency threshold."""

    TEMPORAL_PATTERN = "temporal_pattern"
    """An entity's appearances follow a notable temporal cadence
    (periodic, widening gaps, burst, etc.)."""

    BEHAVIORAL_PATTERN = "behavioral_pattern"
    """An entity's facts or relationships show a consistent behavior
    pattern (e.g., always asks about pricing before churning)."""

    # Future types (uncomment when implemented):
    # COMMUNITY_BELONGS_TO = "community_belongs_to"
    # ANOMALY = "anomaly"
    # CENTRALITY = "centrality"
